### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Marl00** [MarkusBordihn/BOs-Eco-Stack-Manager#2]
Hello !

Can you explain me how the Automatic Cleanup work please ?
I want to put this mod on my server but I want to be pretty sure about how it work and if we can disable it ?
I would like the item despawn stay like vanilla.

Thanks !

**Comment by MarkusBordihn** [comment]
Thanks for your question.

Most of the functionality is detailed in the [wiki](https://github.com/MarkusBordihn/BOs-Eco-Stack-Manager/wiki).

With the latest update, I added a config file that allows you to fine-tune most settings. For example:

```
# Experience Orb Configuration
# Wed Jul 24 20:24:39 CEST 2024
collect_radius=4
move_position_to_last_drop=true
```

```
# Item Entity Configuration
# Wed Jul 24 22:03:52 CEST 2024
allow_list=
collect_radius=3
deny_list=minecraft:diamond_block,minecraft:diamond
max_number_of_items_per_type=32
max_number_of_items_per_world=128
max_stack_size=64
move_position_to_last_drop=false
verification_cycle=64
```

I will add an additional config entry to disable the max number checks of items.

In the current version, you can increase the `max_number_of_items_per_type` and `max_number_of_items_per_world` to a value like 1024 or higher.
