### ISSUE TITLE
[Bug][1.20.1] Stacktraces in console -  java.lang.NoSuchFieldException: value

### ISSUE THREAD

**Issue by ProsperCraft** [MarkusBordihn/BOs-Eco-Stack-Manager#3]
**Minecraft and Mod version** 🐞
Minecraft 1.20.1
Mod version- eco_stack_manager-fabric-1.20.1-1.2.0

**Describe the bug** 🐞
Stacktraces in console
https://gist.githubusercontent.com/ProsperCraft/39e53256bbaf4b28163441eb3a7599a2/raw/09690bfe00f6fd9d649ab40b647a0eed70cfdd7e/gistfile1.txt

**To Reproduce** ⚙️

Set up a dedicated server
kill things
watch console.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩
Modlist-
https://gist.github.com/ProsperCraft/aae826d698a9d646b5588b7b54096386

**Comment by MarkusBordihn** [comment]
Thanks for the report! Could you let me know which launcher you're using? 

Normally, the fields should be mapped correctly, but it looks like your client is expecting `f_20770_` instead of `value`.

I'll move this message to the debug level and add a check for `f_20770_` to fix this.
